version: '2'
services:
  web:
    build: .docker/
    volumes:
      - ./htdocs:/var/www/html:cached
      - ./.docker:/etc/apache2/sites-available
    domainname: mcjc-omeka.l
    hostname: mcjc-omeka.l
    container_name: mcjc-omeka.l
    environment:
      XDEBUG_CONFIG: remote_host=10.254.254.254
    ports:
      - "80:80"
    depends_on:
      - db

  db:
      image: mysql:5.5.47
      volumes:
        - ./db:/docker-entrypoint-initdb.d
      environment:
        MYSQL_DATABASE: 'omeka'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '33308:3306'

volumes:
  mysql-data:
    driver: local
#  omeka-htdocs-sync:
#    external: true
