version: '2'
services:
  web:
    build: .docker/
    volumes:
      - ./htdocs:/var/www/html:cached
      - ./.docker:/etc/apache2/sites-available:cached
    domainname: mcjc-omeka.l
    hostname: mcjc-omeka.l
    container_name: mcjc-omeka.l
    environment:
      XDEBUG_CONFIG: remote_host=10.254.254.254
    ports:
      - "80:80"
    depends_on:
      - db

  db:
      image: mysql:5.7.26
      volumes:
        - ./db:/docker-entrypoint-initdb.d:cached
      environment:
        MYSQL_DATABASE: 'omeka'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '33308:3306'

  compass:
    image: stevevega/compass
    command: watch
    volumes:
      - ./htdocs/themes/berlin_mcjc/sass:/input
      - ./htdocs/themes/berlin_mcjc/css:/output
      - ./htdocs/themes/berlin_mcjc/images:/images

volumes:
  mysql-data:
    driver: local
#  omeka-htdocs-sync:
#    external: true
