<?php

$AUG_2020_TAG_UPDATES = [["oldTag"=>"Hearn’s Grocery","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"Hearns","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"Hern’s Grocery Store","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"School desegregation","newTag"=>"Desegregation","action"=>"REPLACE"],
  ["oldTag"=>"School integration","newTag"=>"Desegregation","action"=>"REPLACE"],
  ["oldTag"=>"School segregation","newTag"=>"Desegregation","action"=>"REPLACE"],
  ["oldTag"=>"Jessie Chavis","newTag"=>"Jesse Chavis","action"=>"REPLACE"],
  ["oldTag"=>"Lucille McDougal","newTag"=>"Lucille McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Lyon's Park","newTag"=>"Lyon Park","action"=>"REPLACE"],
  ["oldTag"=>"M&M Grill","newTag"=>"M&N Grill","action"=>"REPLACE"],
  ["oldTag"=>"Alan McSurely","newTag"=>"Al McSurely","action"=>"REPLACE"],
  ["oldTag"=>"Gil gor","newTag"=>"Bob Gilgor","action"=>"REPLACE"],
  ["oldTag"=>"Goamains Street","newTag"=>"Gomains Avenue","action"=>"REPLACE"],
  ["oldTag"=>"Gomain Avenue","newTag"=>"Gomains Avenue","action"=>"REPLACE"],
  ["oldTag"=>"Grand Street","newTag"=>"Graham Street","action"=>"REPLACE"],
  ["oldTag"=>"Grant Street","newTag"=>"Graham Street","action"=>"REPLACE"],
  ["oldTag"=>"Hall River Baptist Church","newTag"=>"Haw River Baptist [Church]","action"=>"REPLACE"],
  ["oldTag"=>"Houskeeping","newTag"=>"Housekeeping","action"=>"REPLACE"],
  ["oldTag"=>"Johson C. Smith University","newTag"=>"Johnson C. Smith University","action"=>"REPLACE"],
  ["oldTag"=>"Knott's Funeral Home","newTag"=>"Knotts Funeral Home","action"=>"REPLACE"],
  ["oldTag"=>"Lion's Park","newTag"=>"Lyon Park","action"=>"REPLACE"],
  ["oldTag"=>"Lottie Merit","newTag"=>"Lottie Merritt","action"=>"REPLACE"],
  ["oldTag"=>"MacDay Street","newTag"=>"McDade Street","action"=>"REPLACE"],
  ["oldTag"=>"Manly","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"McAuley Street","newTag"=>"McCauley Street","action"=>"REPLACE"],
  ["oldTag"=>"Merit School","newTag"=>"Merritt School","action"=>"REPLACE"],
  ["oldTag"=>"Millette Street","newTag"=>"Mallette Street","action"=>"REPLACE"],
  ["oldTag"=>"Milt By Num","newTag"=>"Milt Bynum","action"=>"REPLACE"],
  ["oldTag"=>"NC mutual","newTag"=>"NC Mutual","action"=>"REPLACE"],
  ["oldTag"=>"Quintin Baker","newTag"=>"Quinton Baker","action"=>"REPLACE"],
  ["oldTag"=>"School board","newTag"=>"School Board","action"=>"REPLACE"],
  ["oldTag"=>"Sprituals","newTag"=>"spirituals","action"=>"REPLACE"],
  ["oldTag"=>"Vickers vs Chapel Hill School Board of Education","newTag"=>"Vickers v. Chapel Hill City Board of Education","action"=>"REPLACE"],
  ["oldTag"=>"Voter Rights Act","newTag"=>"Voting Rights Act","action"=>"REPLACE"],
  ["oldTag"=>"Coach Culton OR Calter?","newTag"=>"-","action"=>"REPLACE"],
  ["oldTag"=>"Coach Pearman","newTag"=>"Coach Peerman","action"=>"REPLACE"],
  ["oldTag"=>"Coach R.O. Kornegay","newTag"=>"Coach Kornegay","action"=>"REPLACE"],
  ["oldTag"=>"Korengas","newTag"=>"Coach Kornegay","action"=>"REPLACE"],
  ["oldTag"=>"R.O. Carnegie","newTag"=>"Coach Kornegay","action"=>"REPLACE"],
  ["oldTag"=>"C.A, Mcdougal","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Mr. C.A. MacDougal","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Mr. C.A. McDougle","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Mrs. C.A. McDougal","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Principal C.A. McDougle","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"[Dr.] Edwin Caldwell","newTag"=>"Edwin Caldwell","action"=>"REPLACE"],
  ["oldTag"=>"[first African American] firefighter","newTag"=>"Firefighter","action"=>"REPLACE"],
  ["oldTag"=>"[first black female] police officer","newTag"=>"Police officer","action"=>"REPLACE"],
  ["oldTag"=>"[R.D. Smith and Euselle B.] Smith Middle School","newTag"=>"Smith Middle School","action"=>"REPLACE"],
  ["oldTag"=>"African American teachers","newTag"=>"Teacher","action"=>"REPLACE"],
  ["oldTag"=>"American Tobacco [Company]","newTag"=>"American Tobacco","action"=>"REPLACE"],
  ["oldTag"=>"Athletes","newTag"=>"Sports; Athletics","action"=>"REPLACE"],
  ["oldTag"=>"Baking","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Band competition","newTag"=>"Band","action"=>"REPLACE"],
  ["oldTag"=>"Band director","newTag"=>"Band","action"=>"REPLACE"],
  ["oldTag"=>"Band tour","newTag"=>"Band","action"=>"REPLACE"],
  ["oldTag"=>"Barbee's Chapel","newTag"=>"Barbee's Chapel","action"=>"REPLACE"],
  ["oldTag"=>"Barbee's Chapel","newTag"=>"Barbee's Chapel Baptist Church","action"=>"REPLACE"],
  ["oldTag"=>"Bougainville","newTag"=>"WWII; World War II","action"=>"REPLACE"],
  ["oldTag"=>"Brook Street","newTag"=>"Brooks Street","action"=>"REPLACE"],
  ["oldTag"=>"Builder[s]","newTag"=>"Builder","action"=>"REPLACE"],
  ["oldTag"=>"Buttermilk buscuits","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Cake","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Camp Bertha","newTag"=>"WWII; World War II","action"=>"REPLACE"],
  ["oldTag"=>"Camp Wallace","newTag"=>"WWII; World War II","action"=>"REPLACE"],
  ["oldTag"=>"Carolina theatre","newTag"=>"Carolina Theater","action"=>"REPLACE"],
  ["oldTag"=>"Carrboro Police Department","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Chapel Hill High","newTag"=>"Chapel Hill High School","action"=>"REPLACE"],
  ["oldTag"=>"Chapel Hill Junior High","newTag"=>"Chapel Hill Junior High School","action"=>"REPLACE"],
  ["oldTag"=>"Chapel Hill Tennis Club","newTag"=>"Sports; Athletics","action"=>"REPLACE"],
  ["oldTag"=>"Chapel Hill town council","newTag"=>"Chapel Hill Town Council","action"=>"REPLACE"],
  ["oldTag"=>"Chitlins","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Christianity","newTag"=>"Faith; Religion","action"=>"REPLACE"],
  ["oldTag"=>"Christmas parade","newTag"=>"Christmas","action"=>"REPLACE"],
  ["oldTag"=>"Church of God","newTag"=>"Chapel Hill Church of God","action"=>"REPLACE"],
  ["oldTag"=>"Class differences","newTag"=>"Socioeconomic difference","action"=>"REPLACE"],
  ["oldTag"=>"Coach [name]","newTag"=>"Coaching","action"=>"REPLACE"],
  ["oldTag"=>"Coach Willie Bradshaw","newTag"=>"Coach [Will] Bradshaw","action"=>"REPLACE"],
  ["oldTag"=>"Colonial Drug Store","newTag"=>"Colonial Drugstore","action"=>"REPLACE"],
  ["oldTag"=>"Community Church","newTag"=>"Community Church of Chapel Hill","action"=>"REPLACE"],
  ["oldTag"=>"Cookbooks","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Crest Street","newTag"=>"Crest Drive","action"=>"REPLACE"],
  ["oldTag"=>"Culbreth","newTag"=>"Culbreth Middle School","action"=>"REPLACE"],
  ["oldTag"=>"CW Stanford","newTag"=>"C.W. Stanford Middle School","action"=>"REPLACE"],
  ["oldTag"=>"David Caldwell","newTag"=>"David Caldwell","action"=>"REPLACE"],
  ["oldTag"=>"Depression food","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Dr. Edwin Caldwell","newTag"=>"Edwin Caldwell","action"=>"REPLACE"],
  ["oldTag"=>"Dr. Frank Graham","newTag"=>"Frank Porter Graham","action"=>"REPLACE"],
  ["oldTag"=>"Dr. Frank Porter Graham","newTag"=>"Frank Porter Graham","action"=>"REPLACE"],
  ["oldTag"=>"Dr. J.R. Manley","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"Dump cooking","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Employment discrimination","newTag"=>"Discrimination","action"=>"REPLACE"],
  ["oldTag"=>"Ephesus School","newTag"=>"Ephesus Elementary School","action"=>"REPLACE"],
  ["oldTag"=>"Estes Hill","newTag"=>"Estes Hills","action"=>"REPLACE"],
  ["oldTag"=>"Exxon","newTag"=>"[Ross] Norwood's service station","action"=>"REPLACE"],
  ["oldTag"=>"Family childcare","newTag"=>"Childcare","action"=>"REPLACE"],
  ["oldTag"=>"Favorite foods","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Fayetteville State","newTag"=>"Fayetteville State University","action"=>"REPLACE"],
  ["oldTag"=>"First Baptist","newTag"=>"First Baptist Church","action"=>"REPLACE"],
  ["oldTag"=>"Football coach","newTag"=>"Coaching","action"=>"REPLACE"],
  ["oldTag"=>"Fried cornbread","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Glenwood Elementary","newTag"=>"Glenwood Elementary School","action"=>"REPLACE"],
  ["oldTag"=>"Glenwood Elementary School","newTag"=>"Glenwood Elementary","action"=>"REPLACE"],
  ["oldTag"=>"Glenwood School","newTag"=>"Glenwood Elementary","action"=>"REPLACE"],
  ["oldTag"=>"Greenbridge Project","newTag"=>"Greenbridge","action"=>"REPLACE"],
  ["oldTag"=>"Guy B. Phillips","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Guy B. Phillips Junior High School","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Guy B. Phillips.","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Guy B. Phillips.","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Hamlet Chapel","newTag"=>"Hamlet Chapel CME","action"=>"REPLACE"],
  ["oldTag"=>"Hamlet’s","newTag"=>"Hamlet Chapel CME","action"=>"REPLACE"],
  ["oldTag"=>"Hamlet’s Chapel","newTag"=>"Hamlet Chapel CME","action"=>"REPLACE"],
  ["oldTag"=>"Hargraves","newTag"=>"Hargraves Community Center","action"=>"REPLACE"],
  ["oldTag"=>"Hargraves Center","newTag"=>"Hargraves Community Center","action"=>"REPLACE"],
  ["oldTag"=>"Hargraves family [history]","newTag"=>"Hargraves family","action"=>"REPLACE"],
  ["oldTag"=>"Haw River Baptist","newTag"=>"Haw River Baptist Church","action"=>"REPLACE"],
  ["oldTag"=>"Hearn's Grocery","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"Hearns","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"Hern's Grocery Store","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"High school football","newTag"=>"Sports; Athletics","action"=>"REPLACE"],
  ["oldTag"=>"Hillsborough prison","newTag"=>"Hillsborough","action"=>"REPLACE"],
  ["oldTag"=>"Hillside","newTag"=>"Hillside High School","action"=>"REPLACE"],
  ["oldTag"=>"Holmes Child Care","newTag"=>"Holmes Daycare","action"=>"REPLACE"],
  ["oldTag"=>"Housing discrimination","newTag"=>"Discrimination","action"=>"REPLACE"],
  ["oldTag"=>"Janitorial work","newTag"=>"Janitor","action"=>"REPLACE"],
  ["oldTag"=>"Janitors’ Association [of UNC]","newTag"=>"Janitors' Association","action"=>"REPLACE"],
  ["oldTag"=>"Jason C. Smith University","newTag"=>"Johnson C. Smith University","action"=>"REPLACE"],
  ["oldTag"=>"Jehovah's Witness","newTag"=>"Faith; Religion","action"=>"REPLACE"],
  ["oldTag"=>"Kappa Sig","newTag"=>"Kappa Sigma","action"=>"REPLACE"],
  ["oldTag"=>"Klan","newTag"=>"KKK","action"=>"REPLACE"],
  ["oldTag"=>"Kornegas","newTag"=>"Coach [R.O.] Kornegay","action"=>"REPLACE"],
  ["oldTag"=>"Ku Klux Klan","newTag"=>"KKK","action"=>"REPLACE"],
  ["oldTag"=>"Laborer","newTag"=>"Labor","action"=>"REPLACE"],
  ["oldTag"=>"Lincoln High","newTag"=>"Lincoln High School","action"=>"REPLACE"],
  ["oldTag"=>"Lyon's Park","newTag"=>"Lyon Park","action"=>"REPLACE"],
  ["oldTag"=>"M&N","newTag"=>"Grill","action"=>"REPLACE"],
  ["oldTag"=>"Male chorus","newTag"=>"St Joseph CME","action"=>"REPLACE"],
  ["oldTag"=>"Mama Dip's","newTag"=>"Mama Dip","action"=>"REPLACE"],
  ["oldTag"=>"Marian Jackson","newTag"=>"Marian Cheek Jackson","action"=>"REPLACE"],
  ["oldTag"=>"Martin Luther King [Jr.]","newTag"=>"Martin Luther King","action"=>"REPLACE"],
  ["oldTag"=>"Martin Luther King [Jr.] assassination","newTag"=>"Martin Luther King assassination","action"=>"REPLACE"],
  ["oldTag"=>"Masonry","newTag"=>"masonry","action"=>"REPLACE"],
  ["oldTag"=>"May Day [celebration]","newTag"=>"May Day","action"=>"REPLACE"],
  ["oldTag"=>"Midwives","newTag"=>"[Midwife]","action"=>"REPLACE"],
  ["oldTag"=>"Military (Navy)","newTag"=>"Navy","action"=>"REPLACE"],
  ["oldTag"=>"Military officer","newTag"=>"Military","action"=>"REPLACE"],
  ["oldTag"=>"Military service","newTag"=>"Military","action"=>"REPLACE"],
  ["oldTag"=>"Miss Rebecca Clark","newTag"=>"Rebecca Clark","action"=>"REPLACE"],
  ["oldTag"=>"Miss Zora Rashkiss","newTag"=>"Zora Rashkiss","action"=>"REPLACE"],
  ["oldTag"=>"Molasses","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Morgan State","newTag"=>"Morgan State University","action"=>"REPLACE"],
  ["oldTag"=>"Mr. Carswell's store","newTag"=>"Colonial Drugstore","action"=>"REPLACE"],
  ["oldTag"=>"NC A&T","newTag"=>"North Carolina A&T","action"=>"REPLACE"],
  ["oldTag"=>"Nick’s","newTag"=>"Grill","action"=>"REPLACE"],
  ["oldTag"=>"Nick’s Grill","newTag"=>"Grill","action"=>"REPLACE"],
  ["oldTag"=>"North Carolina A&T State University","newTag"=>"North Carolina A&T","action"=>"REPLACE"],
  ["oldTag"=>"North Carolina Band and Orchestra Directors Association","newTag"=>"Band","action"=>"REPLACE"],
  ["oldTag"=>"North Carolina Central University","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"North Carolina College for Negroes","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"North Carolina Mutual Life Insurance Company","newTag"=>"North Carolina Mutual","action"=>"REPLACE"],
  ["oldTag"=>"North Side Elementary School","newTag"=>"Northside Elementary school","action"=>"REPLACE"],
  ["oldTag"=>"Northern cooking","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Northside Elementary","newTag"=>"Northside Elementary school","action"=>"REPLACE"],
  ["oldTag"=>"Northside High School","newTag"=>"Northside School","action"=>"REPLACE"],
  ["oldTag"=>"Nursing aid","newTag"=>"Nurse","action"=>"REPLACE"],
  ["oldTag"=>"O'Bryant Chapel","newTag"=>"O'Bryant Chapel AME","action"=>"REPLACE"],
  ["oldTag"=>"Occupations","newTag"=>"Labor","action"=>"REPLACE"],
  ["oldTag"=>"Old Emerson Field","newTag"=>"Emerson Field","action"=>"REPLACE"],
  ["oldTag"=>"Orange Echo","newTag"=>"The Echo","action"=>"REPLACE"],
  ["oldTag"=>"Pastor J.R. Manley","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"Pearl Harbor","newTag"=>"WWII; World War II","action"=>"REPLACE"],
  ["oldTag"=>"Phillips","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Phillips Jr. High","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Pie","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Pit stabbing","newTag"=>"James Cates","action"=>"REPLACE"],
  ["oldTag"=>"Pleasant Grove","newTag"=>"Pleasant Grove Baptist Church","action"=>"REPLACE"],
  ["oldTag"=>"Police intimidation","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Police officer","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Police supervisor","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Police violence","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Police-community relations","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Potter's Field","newTag"=>"Pottersfield","action"=>"REPLACE"],
  ["oldTag"=>"Potters Field","newTag"=>"Pottersfield","action"=>"REPLACE"],
  ["oldTag"=>"Pound cake","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Prejudice","newTag"=>"Racism","action"=>"REPLACE"],
  ["oldTag"=>"President Obama and education","newTag"=>"President Obama","action"=>"REPLACE"],
  ["oldTag"=>"Protesting","newTag"=>"Protest","action"=>"REPLACE"],
  ["oldTag"=>"Protests","newTag"=>"Protest","action"=>"REPLACE"],
  ["oldTag"=>"Public housing [plans]","newTag"=>"Public housing","action"=>"REPLACE"],
  ["oldTag"=>"Public transportation","newTag"=>"Transportation","action"=>"REPLACE"],
  ["oldTag"=>"R. O. Carnegie","newTag"=>"Coach [R.O.] Kornegay","action"=>"REPLACE"],
  ["oldTag"=>"Race consciousness","newTag"=>"Race","action"=>"REPLACE"],
  ["oldTag"=>"Race relations","newTag"=>"Race","action"=>"REPLACE"],
  ["oldTag"=>"Racial comfort","newTag"=>"Race","action"=>"REPLACE"],
  ["oldTag"=>"Racial discrimination","newTag"=>"Racism","action"=>"REPLACE"],
  ["oldTag"=>"Racial prejudice","newTag"=>"Racism","action"=>"REPLACE"],
  ["oldTag"=>"Racial solidarity","newTag"=>"Racism","action"=>"REPLACE"],
  ["oldTag"=>"Racial violence","newTag"=>"Racism","action"=>"REPLACE"],
  ["oldTag"=>"RD Smith","newTag"=>"R.D. Smith","action"=>"REPLACE"],
  ["oldTag"=>"Recipes","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Rev. J.R. Manley","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"Reverend J.R. Manley","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"Reverend JR. Manley","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"Riverside High","newTag"=>"Riverside High School","action"=>"REPLACE"],
  ["oldTag"=>"Robertson Street Center","newTag"=>"Roberson Street Center","action"=>"REPLACE"],
  ["oldTag"=>"Robinson Street","newTag"=>"Roberson Street Center","action"=>"REPLACE"],
  ["oldTag"=>"Rogers Road community","newTag"=>"Rogers Road","action"=>"REPLACE"],
  ["oldTag"=>"School dances","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"School newspaper","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"School punishment","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"School retention","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"School segregation","newTag"=>"Segregation","action"=>"REPLACE"],
  ["oldTag"=>"School system","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"School teacher","newTag"=>"Teacher","action"=>"REPLACE"],
  ["oldTag"=>"School tracking","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"Shaw University","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"Soccer","newTag"=>"Sports; Athletics","action"=>"REPLACE"],
  ["oldTag"=>"Soul food","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Southern cooking","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"St. Joseph's church","newTag"=>"St. Joseph CME Church","action"=>"REPLACE"],
  ["oldTag"=>"St. Joseph's CME Church","newTag"=>"St. Joseph CME Church","action"=>"REPLACE"],
  ["oldTag"=>"St. Paul's AME Church","newTag"=>"St. Paul AME Church","action"=>"REPLACE"],
  ["oldTag"=>"St. Paul's Church","newTag"=>"St. Paul AME Church","action"=>"REPLACE"],
  ["oldTag"=>"St. Paul's Methodist Church","newTag"=>"St. Paul AME Church","action"=>"REPLACE"],
  ["oldTag"=>"State championship","newTag"=>"Sports; Athletics","action"=>"REPLACE"],
  ["oldTag"=>"Student body president","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"Student discipline","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"Substitute teaching","newTag"=>"Teacher","action"=>"REPLACE"],
  ["oldTag"=>"Sunday meal","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Sutton's Drugstore","newTag"=>"Sutton's Drug","action"=>"REPLACE"],
  ["oldTag"=>"Teaching","newTag"=>"Teacher","action"=>"REPLACE"],
  ["oldTag"=>"Teaching children","newTag"=>"Teacher","action"=>"REPLACE"],
  ["oldTag"=>"The Carolina cab","newTag"=>"Carolina cab","action"=>"REPLACE"],
  ["oldTag"=>"The Carolina Inn","newTag"=>"Carolina Inn","action"=>"REPLACE"],
  ["oldTag"=>"The Carolina Inn","newTag"=>"Carolina Inn","action"=>"REPLACE"],
  ["oldTag"=>"The Civil Rights Act","newTag"=>"Civil Rights Act","action"=>"REPLACE"],
  ["oldTag"=>"The Elks","newTag"=>"Elks","action"=>"REPLACE"],
  ["oldTag"=>"The Great Depression","newTag"=>"Great Depression","action"=>"REPLACE"],
  ["oldTag"=>"The Jackson Center","newTag"=>"Jackson Center","action"=>"REPLACE"],
  ["oldTag"=>"The Masons","newTag"=>"Masons","action"=>"REPLACE"],
  ["oldTag"=>"The Orange Echo","newTag"=>"The Echo","action"=>"REPLACE"],
  ["oldTag"=>"The rock pile","newTag"=>"Rock pile","action"=>"REPLACE"],
  ["oldTag"=>"The University of North Carolina at Greensboro","newTag"=>"University of North Carolina at Greensboro","action"=>"REPLACE"],
  ["oldTag"=>"Tobacco factory","newTag"=>"Tobacco","action"=>"REPLACE"],
  ["oldTag"=>"Tomato pudding","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Town council","newTag"=>"Chapel Hill Town Council","action"=>"REPLACE"],
  ["oldTag"=>"Town of Chapel Hill","newTag"=>"Chapel Hill","action"=>"REPLACE"],
  ["oldTag"=>"UNC campus","newTag"=>"UNC","action"=>"REPLACE"],
  ["oldTag"=>"UNC campus health","newTag"=>"UNC","action"=>"REPLACE"],
  ["oldTag"=>"UNC hospital","newTag"=>"UNC Hospitals","action"=>"REPLACE"],
  ["oldTag"=>"UNC-Chapel Hill","newTag"=>"UNC","action"=>"REPLACE"],
  ["oldTag"=>"University Memorial Hospital","newTag"=>"Memorial Hospital","action"=>"REPLACE"],
  ["oldTag"=>"Wage gap","newTag"=>"[low] wages","action"=>"REPLACE"],
  ["oldTag"=>"Wake County School District","newTag"=>"Wake County","action"=>"REPLACE"],
  ["oldTag"=>"Walt’s","newTag"=>"Grill","action"=>"REPLACE"],
  ["oldTag"=>"Watt’s Hotel [discrimination]","newTag"=>"Watt's Hotel","action"=>"REPLACE"],
  ["oldTag"=>"Watts Hotel [discrimination]","newTag"=>"Watts Hotel","action"=>"REPLACE"],
  ["oldTag"=>"Willie D. Bradshaw","newTag"=>"Coach [Will] Bradshaw","action"=>"REPLACE"],
  ["oldTag"=>"Winston Salem State University","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"Winston-Salem State University","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"Winston-Salem Teachers' College","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"Woodward Elementary School","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"Workplace discrimination","newTag"=>"Discrimination","action"=>"REPLACE"],
  ["oldTag"=>"Youth leader","newTag"=>"Youth","action"=>"REPLACE"],
  ["oldTag"=>"A&P","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Abbot Hogan","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Abortion equipment","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Abuse","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Abusive marriage","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Adoption","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"African American neighborhood","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Alamance Community College","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Alcohol","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Alice Neal","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Alzheimer's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"American Indian heritage","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"American Studies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Angela Lee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Apple Chill Festival","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Attorney general","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Aunt Maxine","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"AVID","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Baltimore","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Baptist","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Barn Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Beauty school","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Belk's and feed store","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Bernard Watson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Birch Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Black history","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Boy scout","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Break-ins","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Buck mountain","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Buick car lot","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cancer","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Career","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro baseball park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro Lion's Park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro Parks and Recreation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro Town Hall","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cat baby","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill Parks and Recreation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill Presbyterian Church","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Charliese Cotton","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cherry Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chorus","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"City regional planning","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Civil rights workshop","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Civil service jobs","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Clark","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Clark family","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cobb's Terrace","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Coleman","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"College","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Columbia University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Coming of age","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Community metings","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Community replacement","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Community representation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Computer programming","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Concussions","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cornell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cost of living","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cote d'Ivoire","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Councilville","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Country","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"D.C.","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Damscus Church","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Davidson College","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Delaney Sisters","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Demographic changes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Demographics of McDonald's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Department of Medicine","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Department of Social services","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Deputy Director of the Housing Finance Agency","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Diabetes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dillard High School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dogwood Acres","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Donating clothes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Down Syndrome","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dr. Coleman","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Drama","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Drinking","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Durham Athletic Park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Durham Morning Herald","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"East Baltimore MD","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Election boards","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Elk's Lodge","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Estes Drive","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Europe","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Expansion","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Extended family","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Family awards","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Farmer's Exchange","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Father","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fathers","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Favoritism","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fighting","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Filmore Hall","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Five and dime","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Foreman","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fort Knox","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fort Valley State","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"French language","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Friendships","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Front Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fundraising","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Georgia","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Good neighbor","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Government complicity","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Government regulations","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Government work","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Governor Wallace","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Greece","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hair braiding","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ham's restaurant","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Harriet Tubman","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hawaii","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Health Department","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Herman Foushee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hill Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"HK on J March","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Home conditions","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Home history","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"House fire","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Huggins Hardware","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hurt Hill","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ice House","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Illness","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Intimate Bookshop","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Iowa State","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ivory Coast","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jeff Thomas","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jewish neighbors","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jim Neal","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"John Hope Franklin","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"John R. Hawkins High School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jones","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Kenan Stadium","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Kinky braids","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Languages","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Lawyer","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Leroy","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Levinson college","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Life lessons","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Life lessons","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Lindsay house","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Love","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ma","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mage Henry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Malcolm X","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Markham house","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Marriott","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Maurice Julian's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"McFarlanes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"McLennon","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"McNeil Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Media presence","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Medical professor","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Merritt Bridges Daycare Award","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Migration","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Milkberry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Milton's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Monroe Avenue","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Monsanto","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Morris Mason training room","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mortgage","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mother","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mount Olive","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mt. Sinai Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mug Bell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Muhammed Ali","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Natural hair","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"NC","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Near death experience","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Neighborhood robberies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Neighborhood watch","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"News coverage","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Newspaper","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Northgate mall","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"O'Brien's Ocean Music Store","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Old Chapel Hill cemetery","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Oral history","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Orphan","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Oxford","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Pancake Jamboree","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Paralysis","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Parenting","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Parents","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Parents","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Parker Herndon Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Parks and Recreation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Pettigrew Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Photos","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Piano","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Piedmont Health Services","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Pike Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Place of birth","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Poetry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Policies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Polio","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Politician","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"PORCH","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Porthole","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Present moment","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Preservatives","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Press intelligence","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Princeton University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"PROD","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Prom","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Protest organization","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Psychology","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Pullen Park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Punishment","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Radicals","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Raising animals","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Raleigh","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ralston Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rebecca Clark Award","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rebellion","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Regressive trends","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Research Triangle","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Researcher","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Residential transitions","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Retiring","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Reverend Eubanks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rhodes scholar","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rialto Theater","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Robin's Clothing Store","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rock quarry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Roommates","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rose's ROTC","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Salisbury","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Scarborough buildings","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Science","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Senior center","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Seymour Senior Center","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Shaw Elementary School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Single family homes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Social Interests Group Club","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Social Security","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Social work","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Social workers","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Sonya Stone","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Southern States","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Southern women","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Spheres of influence","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Statesville","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Student meetings","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Suicidal student","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Swain Hall","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Syracuse University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Teenage pregnancy","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Telluride Program","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"That off","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"The National Science Foundation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"The Shadow","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Third Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Time of birth","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Town and campus","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Town bureaucracy","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Travel","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Trustee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Turkey","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Umstead Park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"UNC health care","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Uncle Remus","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Uniting the neighborhood","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University of Georgia","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University of Maryland","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University of Texas","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University professor","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Upward Bound","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Upward mobility","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Validator","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Virginia State University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Virginia Union University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Wake Forest University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Walltown Elementary School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Washington","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Wedding","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"West Virginia State","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"West Virginia State University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"White allies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"White flight","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Wilson library","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Women's Studies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Woolworth","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Wright School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Yale University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mason & Nick’s Grill","newTag"=>"Nick's","action"=>"ADD"],
  ["oldTag"=>"","newTag"=>"African American business; Black owned business/Black business","action"=>"ADD"],
  ["oldTag"=>"Army","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"Baseball","newTag"=>"Sports; Athletics","action"=>"ADD"],
  ["oldTag"=>"Basketball","newTag"=>"Sports; Athletics","action"=>"ADD"],
  ["oldTag"=>"Draft","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"Fayetteville State University","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"Football","newTag"=>"Sports; Athletics","action"=>"ADD"],
  ["oldTag"=>"Johnson C. Smith University","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"M&N Grill   KEEP TAG","newTag"=>"Nick's","action"=>"ADD"],
  ["oldTag"=>"National Guard","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"Navy","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"NCCU","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"NCCU","newTag"=>"North Carolina Central University","action"=>"ADD"],
  ["oldTag"=>"Nick’s Grill   KEEP TAG","newTag"=>"Nick's","action"=>"ADD"],
  ["oldTag"=>"North Carolina A&T","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"North Carolina College for Negroes","newTag"=>"North Carolina Central University","action"=>"ADD"],
  ["oldTag"=>"Roberson Street Center","newTag"=>"Hargraves Community Center","action"=>"ADD"]
];
