<?php

$AUG_2020_TAG_UPDATES = [
  ["oldTag"=>"Hearn’s grocery","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"Hearns","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"Hern’s Grocery Store","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"school desegregation","newTag"=>"Desegregation","action"=>"REPLACE"],
  ["oldTag"=>"School integration","newTag"=>"Desegregation","action"=>"REPLACE"],
  ["oldTag"=>"School segregation","newTag"=>"Desegregation","action"=>"REPLACE"],
  ["oldTag"=>"Jessie Chavis","newTag"=>"Jesse Chavis","action"=>"REPLACE"],
  ["oldTag"=>"Lucille McDougal","newTag"=>"Lucille McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Lyons Park","newTag"=>"Lyon Park","action"=>"REPLACE"],
  ["oldTag"=>"M&M Grill","newTag"=>"M&N Grill","action"=>"REPLACE"],
  ["oldTag"=>"Alan McSurely","newTag"=>"Al McSurely","action"=>"REPLACE"],
  ["oldTag"=>"Gil Gore","newTag"=>"Bob Gilgor","action"=>"REPLACE"],
  ["oldTag"=>"Gomains Street","newTag"=>"Gomains Avenue","action"=>"REPLACE"],
  ["oldTag"=>"Gomain Avenue","newTag"=>"Gomains Avenue","action"=>"REPLACE"],
  ["oldTag"=>"Grand Street","newTag"=>"Graham Street","action"=>"REPLACE"],
  ["oldTag"=>"Grant Street","newTag"=>"Graham Street","action"=>"REPLACE"],
  ["oldTag"=>"Hall River Baptist Church","newTag"=>"Haw River Baptist [Church]","action"=>"REPLACE"],
  ["oldTag"=>"Houskeeping","newTag"=>"Housekeeping","action"=>"REPLACE"],
  ["oldTag"=>"Johson C. Smith University","newTag"=>"Johnson C. Smith University","action"=>"REPLACE"],
  ["oldTag"=>"Knott's Funeral Home","newTag"=>"Knotts Funeral Home","action"=>"REPLACE"],
  ["oldTag"=>"Lion's Park","newTag"=>"Lyon Park","action"=>"REPLACE"],
  ["oldTag"=>"Lottie Merit","newTag"=>"Lottie Merritt","action"=>"REPLACE"],
  ["oldTag"=>"MacDay Street","newTag"=>"McDade Street","action"=>"REPLACE"],
  ["oldTag"=>"McAuley Street","newTag"=>"McCauley Street","action"=>"REPLACE"],
  ["oldTag"=>"Merit School","newTag"=>"Merritt School","action"=>"REPLACE"],
  ["oldTag"=>"Millette Street","newTag"=>"Mallette Street","action"=>"REPLACE"],
  ["oldTag"=>"Milt By Num","newTag"=>"Milt Bynum","action"=>"REPLACE"],
  ["oldTag"=>"NC mutual","newTag"=>"NC Mutual","action"=>"REPLACE"],
  ["oldTag"=>"Quintin Baker","newTag"=>"Quinton Baker","action"=>"REPLACE"],
  ["oldTag"=>"School board","newTag"=>"School Board","action"=>"REPLACE"],
  ["oldTag"=>"Sprituals","newTag"=>"spirituals","action"=>"REPLACE"],
  ["oldTag"=>"Vickers vs. Chapel Hill School Board of Education","newTag"=>"Vickers v. Chapel Hill City Board of Education","action"=>"REPLACE"],
  ["oldTag"=>"Voters Rights Act","newTag"=>"Voting Rights Act","action"=>"REPLACE"],
  ["oldTag"=>"Coach Culton","newTag"=>"-","action"=>"REPLACE"],
  ["oldTag"=>"Coach Pearman","newTag"=>"Coach Peerman","action"=>"REPLACE"],
  ["oldTag"=>"Coach R.O. Kornegay","newTag"=>"Coach Kornegay","action"=>"REPLACE"],
  ["oldTag"=>"Korengas","newTag"=>"Kornegas","action"=>"REPLACE"],
  ["oldTag"=>"R.O. Carnegie","newTag"=>"Coach Kornegay","action"=>"REPLACE"],
  ["oldTag"=>"C. A. Mcdougal","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Mr. C. A. MacDougal","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Mr. C.A. McDougle","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Mr. C. A. McDougal","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Principal C.A. McDougle","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Dr. Edwin Caldwell","newTag"=>"Edwin Caldwell","action"=>"REPLACE"],
  ["oldTag"=>"first African American firefighter","newTag"=>"Firefighter","action"=>"REPLACE"],
  ["oldTag"=>"first black female police officer","newTag"=>"Police officer","action"=>"REPLACE"],
  ["oldTag"=>"R.D. Smith and Euselle B. Smith Middle School","newTag"=>"Smith Middle School","action"=>"REPLACE"],
  ["oldTag"=>"African American teachers","newTag"=>"Teacher","action"=>"REPLACE"],
  ["oldTag"=>"American Tobacco Company","newTag"=>"American Tobacco","action"=>"REPLACE"],
  ["oldTag"=>"Athletes","newTag"=>"Sports; Athletics","action"=>"REPLACE"],
  ["oldTag"=>"Baking","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Band competition","newTag"=>"Band","action"=>"REPLACE"],
  ["oldTag"=>"Band director","newTag"=>"Band","action"=>"REPLACE"],
  ["oldTag"=>"Band tour","newTag"=>"Band","action"=>"REPLACE"],
  ["oldTag"=>"Barbee's Chapel","newTag"=>"Barbee's Chapel","action"=>"REPLACE"],
  ["oldTag"=>"Barbee's Chapel","newTag"=>"Barbee's Chapel Baptist Church","action"=>"REPLACE"],
  ["oldTag"=>"Bougainville","newTag"=>"WWII; World War II","action"=>"REPLACE"],
  ["oldTag"=>"Brook Street","newTag"=>"Brooks Street","action"=>"REPLACE"],
  ["oldTag"=>"Builders","newTag"=>"Builder","action"=>"REPLACE"],
  ["oldTag"=>"Buttermilk biscuits","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Cake","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Camp Bertha","newTag"=>"WWII; World War II","action"=>"REPLACE"],
  ["oldTag"=>"Camp Wallace","newTag"=>"WWII; World War II","action"=>"REPLACE"],
  ["oldTag"=>"Carolina theatre","newTag"=>"Carolina Theater","action"=>"REPLACE"],
  ["oldTag"=>"Carrboro Police Department","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Chapel Hill High","newTag"=>"Chapel Hill High School","action"=>"REPLACE"],
  ["oldTag"=>"Chapel Hill Junior High","newTag"=>"Chapel Hill Junior High School","action"=>"REPLACE"],
  ["oldTag"=>"Chapel Hill Tennis Club","newTag"=>"Sports; Athletics","action"=>"REPLACE"],
  ["oldTag"=>"Chapel Hill town council","newTag"=>"Chapel Hill Town Council","action"=>"REPLACE"],
  ["oldTag"=>"Chitlins","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Christianity","newTag"=>"Faith; Religion","action"=>"REPLACE"],
  ["oldTag"=>"Christmas parade","newTag"=>"Christmas","action"=>"REPLACE"],
  ["oldTag"=>"Church of God","newTag"=>"Chapel Hill Church of God","action"=>"REPLACE"],
  ["oldTag"=>"Class differences","newTag"=>"Socioeconomic difference","action"=>"REPLACE"],
  ["oldTag"=>"Coach Willie Bradshaw","newTag"=>"Coach [Will] Bradshaw","action"=>"REPLACE"],
  ["oldTag"=>"Colonial Drug Store","newTag"=>"Colonial Drugstore","action"=>"REPLACE"],
  ["oldTag"=>"Community Church","newTag"=>"Community Church of Chapel Hill","action"=>"REPLACE"],
  ["oldTag"=>"Cookbooks","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Crest Street","newTag"=>"Crest Drive","action"=>"REPLACE"],
  ["oldTag"=>"Culbreth","newTag"=>"Culbreth Middle School","action"=>"REPLACE"],
  ["oldTag"=>"CW Stanford","newTag"=>"C.W. Stanford Middle School","action"=>"REPLACE"],
  ["oldTag"=>"David Caldwell","newTag"=>"David Caldwell","action"=>"REPLACE"],
  ["oldTag"=>"Depression food","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Dr. Edwin Caldwell","newTag"=>"Edwin Caldwell","action"=>"REPLACE"],
  ["oldTag"=>"Dr. Frank Graham","newTag"=>"Frank Porter Graham","action"=>"REPLACE"],
  ["oldTag"=>"Dr. Frank Porter Graham","newTag"=>"Frank Porter Graham","action"=>"REPLACE"],
  ["oldTag"=>"Dr. J. R. Manley","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"Dump cooking","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Employment discrimination","newTag"=>"Discrimination","action"=>"REPLACE"],
  ["oldTag"=>"Ephesus School","newTag"=>"Ephesus Elementary School","action"=>"REPLACE"],
  ["oldTag"=>"Estes Hill","newTag"=>"Estes Hills","action"=>"REPLACE"],
  ["oldTag"=>"Exxon","newTag"=>"[Ross] Norwood's service station","action"=>"REPLACE"],
  ["oldTag"=>"Family childcare","newTag"=>"Childcare","action"=>"REPLACE"],
  ["oldTag"=>"Favorite foods","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Fayetteville State","newTag"=>"Fayetteville State University","action"=>"REPLACE"],
  ["oldTag"=>"First Baptist","newTag"=>"First Baptist Church","action"=>"REPLACE"],
  ["oldTag"=>"Football coach","newTag"=>"Coaching","action"=>"REPLACE"],
  ["oldTag"=>"Fried cornbread","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Glenwood Elementary","newTag"=>"Glenwood Elementary School","action"=>"REPLACE"],
  ["oldTag"=>"Glenwood Elementary School","newTag"=>"Glenwood Elementary","action"=>"REPLACE"],
  ["oldTag"=>"Glenwood School","newTag"=>"Glenwood Elementary","action"=>"REPLACE"],
  ["oldTag"=>"Greenbridge Project","newTag"=>"Greenbridge","action"=>"REPLACE"],
  ["oldTag"=>"Guy B. Phillips","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Guy B. Phillips Junior High School","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Guy B. Phillips.","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Hamlet Chapel","newTag"=>"Hamlet Chapel CME","action"=>"REPLACE"],
  ["oldTag"=>"Hamlet's","newTag"=>"Hamlet Chapel CME","action"=>"REPLACE"],
  ["oldTag"=>"Hamlet’s Chapel","newTag"=>"Hamlet Chapel CME","action"=>"REPLACE"],
  ["oldTag"=>"Hargraves","newTag"=>"Hargraves Community Center","action"=>"REPLACE"],
  ["oldTag"=>"Hargraves Center","newTag"=>"Hargraves Community Center","action"=>"REPLACE"],
  ["oldTag"=>"Hargraves family history","newTag"=>"Hargraves family","action"=>"REPLACE"],
  ["oldTag"=>"Haw River Baptist","newTag"=>"Haw River Baptist Church","action"=>"REPLACE"],
  ["oldTag"=>"Hearn's Grocery","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"Hearns","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"Hern's Grocery Store","newTag"=>"Hearn Grocery","action"=>"REPLACE"],
  ["oldTag"=>"High school football","newTag"=>"Sports; Athletics","action"=>"REPLACE"],
  ["oldTag"=>"Hillsborough prison","newTag"=>"Hillsborough","action"=>"REPLACE"],
  ["oldTag"=>"Hillside","newTag"=>"Hillside High School","action"=>"REPLACE"],
  ["oldTag"=>"Holmes Child Care","newTag"=>"Holmes Daycare","action"=>"REPLACE"],
  ["oldTag"=>"Housing discrimination","newTag"=>"Discrimination","action"=>"REPLACE"],
  ["oldTag"=>"Janitorial work","newTag"=>"Janitor","action"=>"REPLACE"],
  ["oldTag"=>"Janitors’ Association of UNC","newTag"=>"Janitors' Association","action"=>"REPLACE"],
  ["oldTag"=>"Jason C. Smith University","newTag"=>"Johnson C. Smith University","action"=>"REPLACE"],
  ["oldTag"=>"Jehovah's Witness","newTag"=>"Faith; Religion","action"=>"REPLACE"],
  ["oldTag"=>"Kappa Sig","newTag"=>"Kappa Sigma","action"=>"REPLACE"],
  ["oldTag"=>"Kornegas","newTag"=>"Coach [R.O.] Kornegay","action"=>"REPLACE"],
  ["oldTag"=>"Ku Klux Klan","newTag"=>"KKK","action"=>"REPLACE"],
  ["oldTag"=>"Laborer","newTag"=>"Labor","action"=>"REPLACE"],
  ["oldTag"=>"Lincoln High","newTag"=>"Lincoln High School","action"=>"REPLACE"],
  ["oldTag"=>"Lyon's Park","newTag"=>"Lyon Park","action"=>"REPLACE"],
  ["oldTag"=>"Male chorus","newTag"=>"St Joseph CME","action"=>"REPLACE"],
  ["oldTag"=>"Mama Dip's","newTag"=>"Mama Dip","action"=>"REPLACE"],
  ["oldTag"=>"Marian Jackson","newTag"=>"Marian Cheek Jackson","action"=>"REPLACE"],
  ["oldTag"=>"Martin Luther King Jr.","newTag"=>"Martin Luther King","action"=>"REPLACE"],
  ["oldTag"=>"Martin Luther King Jr. assassination","newTag"=>"Martin Luther King assassination","action"=>"REPLACE"],
  ["oldTag"=>"Masonry","newTag"=>"masonry","action"=>"REPLACE"],
  ["oldTag"=>"May Day Celebration","newTag"=>"May Day","action"=>"REPLACE"],
  ["oldTag"=>"Midwives","newTag"=>"[Midwife]","action"=>"REPLACE"],
  ["oldTag"=>"Military (Navy)","newTag"=>"Navy","action"=>"REPLACE"],
  ["oldTag"=>"Military officer","newTag"=>"Military","action"=>"REPLACE"],
  ["oldTag"=>"Military service","newTag"=>"Military","action"=>"REPLACE"],
  ["oldTag"=>"Miss Rebecca Clark","newTag"=>"Rebecca Clark","action"=>"REPLACE"],
  ["oldTag"=>"Miss Zora Rashkis","newTag"=>"Zora Rashkiss","action"=>"REPLACE"],
  ["oldTag"=>"Molasses","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Morgan State","newTag"=>"Morgan State University","action"=>"REPLACE"],
  ["oldTag"=>"Mr. Carswell's store","newTag"=>"Colonial Drugstore","action"=>"REPLACE"],
  ["oldTag"=>"NC A&T","newTag"=>"North Carolina A&T","action"=>"REPLACE"],
  ["oldTag"=>"Nick's","newTag"=>"Grill","action"=>"REPLACE"],
  ["oldTag"=>"Nick's grill","newTag"=>"Grill","action"=>"REPLACE"],
  ["oldTag"=>"North Carolina A&T State University","newTag"=>"North Carolina A&T","action"=>"REPLACE"],
  ["oldTag"=>"North Carolina Band and Orchestra Directors Association","newTag"=>"Band","action"=>"REPLACE"],
  ["oldTag"=>"North Carolina Central University","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"North Carolina College for Negroes","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"North Carolina Mutual Life Insurance Company","newTag"=>"North Carolina Mutual","action"=>"REPLACE"],
  ["oldTag"=>"North Side Elementary School","newTag"=>"Northside Elementary school","action"=>"REPLACE"],
  ["oldTag"=>"Northern cooking","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Northside Elementary","newTag"=>"Northside Elementary school","action"=>"REPLACE"],
  ["oldTag"=>"Northside High School","newTag"=>"Northside School","action"=>"REPLACE"],
  ["oldTag"=>"Nursing aid","newTag"=>"Nurse","action"=>"REPLACE"],
  ["oldTag"=>"O'Bryant Chapel [AME]","newTag"=>"O'Bryant Chapel AME","action"=>"REPLACE"],
  ["oldTag"=>"Occupations","newTag"=>"Labor","action"=>"REPLACE"],
  ["oldTag"=>"Old Emerson Field","newTag"=>"Emerson Field","action"=>"REPLACE"],
  ["oldTag"=>"Orange Echo","newTag"=>"The Echo","action"=>"REPLACE"],
  ["oldTag"=>"Pastor J.R. Manley","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"Pearl Harbor","newTag"=>"WWII; World War II","action"=>"REPLACE"],
  ["oldTag"=>"Phillips","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Phillips Jr. High","newTag"=>"Guy B. Phillips Junior High","action"=>"REPLACE"],
  ["oldTag"=>"Pie","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Pit stabbing","newTag"=>"James Cates","action"=>"REPLACE"],
  ["oldTag"=>"Pleasant Grove","newTag"=>"Pleasant Grove Baptist Church","action"=>"REPLACE"],
  ["oldTag"=>"Police intimidation","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Police officer","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Police supervisor","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Police violence","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Police-community relations","newTag"=>"Police","action"=>"REPLACE"],
  ["oldTag"=>"Potter's Field","newTag"=>"Pottersfield","action"=>"REPLACE"],
  ["oldTag"=>"Potters Field","newTag"=>"Pottersfield","action"=>"REPLACE"],
  ["oldTag"=>"Pound cake","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Prejudice","newTag"=>"Racism","action"=>"REPLACE"],
  ["oldTag"=>"President Obama and education","newTag"=>"President Obama","action"=>"REPLACE"],
  ["oldTag"=>"Protesting","newTag"=>"Protest","action"=>"REPLACE"],
  ["oldTag"=>"Protests","newTag"=>"Protest","action"=>"REPLACE"],
  ["oldTag"=>"Public housing plans","newTag"=>"Public housing","action"=>"REPLACE"],
  ["oldTag"=>"Public transportation","newTag"=>"Transportation","action"=>"REPLACE"],
  ["oldTag"=>"Race consciousness","newTag"=>"Race","action"=>"REPLACE"],
  ["oldTag"=>"Race relations","newTag"=>"Race","action"=>"REPLACE"],
  ["oldTag"=>"Racial comfort","newTag"=>"Race","action"=>"REPLACE"],
  ["oldTag"=>"Racial prejudice","newTag"=>"Racism","action"=>"REPLACE"],
  ["oldTag"=>"Racial solidarity","newTag"=>"Racism","action"=>"REPLACE"],
  ["oldTag"=>"Racial violence","newTag"=>"Racism","action"=>"REPLACE"],
  ["oldTag"=>"RD Smith","newTag"=>"R.D. Smith","action"=>"REPLACE"],
  ["oldTag"=>"Recipes","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Rev. J. R. Manley","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"Reverend J. R. Manley","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"Reverend JR. Manley","newTag"=>"J.R. Manley","action"=>"REPLACE"],
  ["oldTag"=>"Riverside High","newTag"=>"Riverside High School","action"=>"REPLACE"],
  ["oldTag"=>"Robertson Street Community Center","newTag"=>"Roberson Street Center","action"=>"REPLACE"],
  ["oldTag"=>"Robinson Street","newTag"=>"Roberson Street Center","action"=>"REPLACE"],
  ["oldTag"=>"Rogers Road community","newTag"=>"Rogers Road","action"=>"REPLACE"],
  ["oldTag"=>"School dances","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"school newspaper","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"School punishment","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"School retention","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"school segregation","newTag"=>"Segregation","action"=>"REPLACE"],
  ["oldTag"=>"School system","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"School teacher","newTag"=>"Teacher","action"=>"REPLACE"],
  ["oldTag"=>"School tracking","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"Shaw University","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"Soccer","newTag"=>"Sports; Athletics","action"=>"REPLACE"],
  ["oldTag"=>"Soul food","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Southern cooking","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"St. Joseph's church","newTag"=>"St. Joseph CME Church","action"=>"REPLACE"],
  ["oldTag"=>"St. Joseph's CME Church","newTag"=>"St. Joseph CME Church","action"=>"REPLACE"],
  ["oldTag"=>"St. Paul's AME Church","newTag"=>"St. Paul AME Church","action"=>"REPLACE"],
  ["oldTag"=>"St. Paul's Church","newTag"=>"St. Paul AME Church","action"=>"REPLACE"],
  ["oldTag"=>"St. Paul's Methodist Church","newTag"=>"St. Paul AME Church","action"=>"REPLACE"],
  ["oldTag"=>"State championship","newTag"=>"Sports; Athletics","action"=>"REPLACE"],
  ["oldTag"=>"Student body president","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"Student discipline","newTag"=>"School experiences","action"=>"REPLACE"],
  ["oldTag"=>"Substitute teaching","newTag"=>"Teacher","action"=>"REPLACE"],
  ["oldTag"=>"Sunday meal","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Sutton's Drugstore","newTag"=>"Sutton's Drug","action"=>"REPLACE"],
  ["oldTag"=>"Teaching","newTag"=>"Teacher","action"=>"REPLACE"],
  ["oldTag"=>"Teaching children","newTag"=>"Teacher","action"=>"REPLACE"],
  ["oldTag"=>"The Carolina cab","newTag"=>"Carolina cab","action"=>"REPLACE"],
  ["oldTag"=>"The Carolina Inn","newTag"=>"Carolina Inn","action"=>"REPLACE"],
  ["oldTag"=>"The Civil Rights Act","newTag"=>"Civil Rights Act","action"=>"REPLACE"],
  ["oldTag"=>"The Elks","newTag"=>"Elks","action"=>"REPLACE"],
  ["oldTag"=>"The Great Depression","newTag"=>"Great Depression","action"=>"REPLACE"],
  ["oldTag"=>"The Jackson Center","newTag"=>"Jackson Center","action"=>"REPLACE"],
  ["oldTag"=>"The Masons","newTag"=>"Masons","action"=>"REPLACE"],
  ["oldTag"=>"The Orange Echo","newTag"=>"The Echo","action"=>"REPLACE"],
  ["oldTag"=>"The rock pile","newTag"=>"Rock pile","action"=>"REPLACE"],
  ["oldTag"=>"The University of North Carolina at Greensboro","newTag"=>"University of North Carolina at Greensboro","action"=>"REPLACE"],
  ["oldTag"=>"Tobacco factory","newTag"=>"Tobacco","action"=>"REPLACE"],
  ["oldTag"=>"Tomato pudding","newTag"=>"Food; Foodways; Cooking","action"=>"REPLACE"],
  ["oldTag"=>"Town council","newTag"=>"Chapel Hill Town Council","action"=>"REPLACE"],
  ["oldTag"=>"Town of Chapel Hill","newTag"=>"Chapel Hill","action"=>"REPLACE"],
  ["oldTag"=>"UNC campus","newTag"=>"UNC","action"=>"REPLACE"],
  ["oldTag"=>"UNC campus health","newTag"=>"UNC","action"=>"REPLACE"],
  ["oldTag"=>"UNC hospital","newTag"=>"UNC Hospitals","action"=>"REPLACE"],
  ["oldTag"=>"UNC-Chapel Hill","newTag"=>"UNC","action"=>"REPLACE"],
  ["oldTag"=>"University Memorial Hospital","newTag"=>"Memorial Hospital","action"=>"REPLACE"],
  ["oldTag"=>"Wage gap","newTag"=>"[low] wages","action"=>"REPLACE"],
  ["oldTag"=>"Wake County School District","newTag"=>"Wake County","action"=>"REPLACE"],
  ["oldTag"=>"Watt’s Hotel discrimination","newTag"=>"Watt's Hotel","action"=>"REPLACE"],
  ["oldTag"=>"Willie D. Bradshaw","newTag"=>"Coach [Will] Bradshaw","action"=>"REPLACE"],
  ["oldTag"=>"Winston-Salem State University","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"Winston-Salem State University","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"Winston-Salem Teachers' College","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"Woodward Elementary School","newTag"=>"HBCU","action"=>"REPLACE"],
  ["oldTag"=>"Workplace discrimination","newTag"=>"Discrimination","action"=>"REPLACE"],
  ["oldTag"=>"Youth leader","newTag"=>"Youth","action"=>"REPLACE"],
  ["oldTag"=>"A&P","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Abbot Hogan","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Abortion equipment","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Abuse","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Abusive marriage","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Adoption","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"African American neighborhood","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Alamance Community College","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Alcohol","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Alice Neal","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Alzheimer's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"American Indian heritage","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"American Studies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Angela Lee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Apple Chill Festival","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Attorney general","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Aunt Maxine","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"AVID","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Baltimore","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Baptist","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Barn Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Beauty school","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Belk's and feed store","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Bernard Watson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Birch Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Black history","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Boy scout","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Break-ins","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Buck mountain","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Buick car lot","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cancer","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Career","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrborro baseball park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro Lion's Park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro Parks and Recreation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro Town Hall","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cat baby","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill Parks and Recreation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill Presbyterian Church","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Charlese Cotton","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cherry Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chorus","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"City regional planning","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Civil rights workshop","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Civil service jobs","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Clark","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Clark family","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cobb's Terrace","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Coleman","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"College","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Columbia University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Coming of age","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Community meetings","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Community replacement","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Community representation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Computer programming","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Concussions","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cornell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cost of living","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cote d'Ivoire","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Councilville","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Country","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"D.C.","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Damascus Church","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Davidson College","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Delaney Sisters","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Demographic changes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Demographics of McDonald's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Department of Medicine","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Department of Social services","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Deputy Director of the Housing Finance Agency","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Diabetes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dillard High School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dogwood Acres","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Donating clothes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Down Syndrome","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dr. Coleman","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Drama","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Drinking","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Durham Athletic Park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Durham Morning Herald","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"East Baltimore MD","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Election boards","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Elk's Lodge","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Estes Drive","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Europe","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Expansion","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Extended family","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Family awards","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Farmer's Exchange","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Father","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fathers","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Favoritism","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fighting","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fillmore Hall","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Five and dime","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Foreman","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fort Knox","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fort Valley State","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"French language","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Friendships","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Front Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fundraising","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Georgia","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Good neighbor","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Government complicity","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Government regulations","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Government work","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Governor Wallace","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Greece","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hair braiding","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ham's restaurant","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Harriet Tubman","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hawaii","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Health Department","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Herman Foushee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hill Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"HK on J March","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Home conditions","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Home history","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"House fire","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Huggins Hardware","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hurt Hill","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ice House","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Illness","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Intimate Book Shop","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Iowa State","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ivory Coast","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jeff Thomas","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jewish neighbors","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jim Neal","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"John Hope Franklin","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"John R. Hawkins High School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jones","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Kenan Stadium","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Kinky braids","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Languages","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Lawyer","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Leroy","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Levinson college","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"life lessons","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Lindsay house","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Love","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ma","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mage Harry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Malcolm X","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Markham house","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Marriot","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Maurice Julian's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"McFarlanes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"McLennon","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"McNeil Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Media presence","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Medical professor","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Merritt Bridges Daycare Award","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Migration","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Milkberry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Milton's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Monroe Avenue","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Monsanto","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Morris Mason training room","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mortgage","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mother","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mount Olive","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mt. Sinai Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mug Bell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Muhammad Ali","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Natural hair","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"NC","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Near death experience","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"neighborhood robberies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"neighbordhood watch meetings","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"News coverage","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Newspaper","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Northgate mall","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"O'Brien's Ocean Music Store","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Old Chapel Hill cemetery","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Oral history","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Orphan","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Oxford","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Pancake Jamboree","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Paralysis","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Parenting","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"parents","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Parker Herndon Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Parks and Recreation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Pettigrew Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Photos","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Piano","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Piedmont Health Services","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Pike Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Place of birth","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Poetry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Policies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Polio","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Politician","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"PORCH","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Porthole","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Present moment","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Preservatives","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Press intelligence","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Princeton University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"PROD","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Prom","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Protest organization","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Psychology","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Pullen Park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Punishment","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Radicals","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Raising animals","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Raleigh","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ralston Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rebecca Clark Award","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rebellion","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Regressive trends","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Research Triangle","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Researcher","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Residential transitions","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Retiring","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Reverend Eubanks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rhodes scholar","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rialto Theater","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Robin's Clothing Store","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rock quarry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Roommates","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rose's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Salisbury","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Scarborough buildings","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Science","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Senior center","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Seymour Senior Center","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Shaw Elementary School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Single family homes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Social Interests Group Club","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Social Security","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Social work","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Social workers","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Sonya Stone","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Southern States","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Southern women","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Spheres of influence","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Statesville","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Student meetings","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Suicidal student","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Swain Hall","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Syracuse University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Teenage pregnancy","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Telluride Program","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"That off","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"The National Science Foundation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"The Shadow","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Third Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Time of birth","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Town and campus","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Town bureaucracy","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Travel","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Trustee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Turkey","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Umstead Park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"UNC health care","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Uncle Remus","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Uniting the neighborhood","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University of Georgia","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University of Maryland","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University of Texas","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University professor","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Upward Bound","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Upward mobility","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Validator","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Virginia State University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Virginia Union University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Wake Forest University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Waltown Elementary School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Washington","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Wedding","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"West Virginia State","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"West Virginia State University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"White allies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"White flight","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Wilson library","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Women's Studies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Woolworth","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Wright School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Yale University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mason and Nick’s Grill","newTag"=>"Nick's","action"=>"ADD"],
  ["oldTag"=>"Army","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"Baseball","newTag"=>"Sports; Athletics","action"=>"ADD"],
  ["oldTag"=>"Basketball","newTag"=>"Sports; Athletics","action"=>"ADD"],
  ["oldTag"=>"Draft","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"Fayetteville State University","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"Football","newTag"=>"Sports; Athletics","action"=>"ADD"],
  ["oldTag"=>"Johnson C. Smith University","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"National Guard","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"Navy","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"NCCU","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"NCCU","newTag"=>"North Carolina Central University","action"=>"ADD"],
  ["oldTag"=>"Nick’s Grill","newTag"=>"Nick's","action"=>"ADD"],
  ["oldTag"=>"North Carolina A&T","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"North Carolina College for Negroes","newTag"=>"North Carolina Central University","action"=>"ADD"],
  ["oldTag"=>"Roberson Street Center","newTag"=>"Hargraves Community Center","action"=>"ADD"],
  ["oldTag"=>"Basketball","newTag"=>"Sports; Athletics","action"=>"ADD"],
  ["oldTag"=>"Draft","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"Fayetteville State University","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"Football","newTag"=>"Sports; Athletics","action"=>"ADD"],
  ["oldTag"=>"Johnson C. Smith University","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"M&N Grill   KEEP TAG","newTag"=>"Nick's","action"=>"ADD"],
  ["oldTag"=>"National Guard","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"Navy","newTag"=>"Military; Armed Forces","action"=>"ADD"],
  ["oldTag"=>"NCCU","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"NCCU","newTag"=>"North Carolina Central University","action"=>"ADD"],
  ["oldTag"=>"Nick’s Grill   KEEP TAG","newTag"=>"Nick's","action"=>"ADD"],
  ["oldTag"=>"North Carolina A&T","newTag"=>"HBCU","action"=>"ADD"],
  ["oldTag"=>"North Carolina College for Negroes","newTag"=>"North Carolina Central University","action"=>"ADD"],
  ["oldTag"=>"Roberson Street Center","newTag"=>"Hargraves Community Center","action"=>"ADD"],
];

$MAR_2021_TAG_UPDATES = [
  ["oldTag"=>"[Midwife]","newTag"=>"Midwife","action"=>"REPLACE"],
  ["oldTag"=>"Barbee's Chapel Baptist Church","newTag"=>"Barbee’s Chapel","action"=>"REPLACE"],
  ["oldTag"=>"black business","newTag"=>"Black business","action"=>"REPLACE"],
  ["oldTag"=>"black cemetery","newTag"=>"Black cemetery","action"=>"REPLACE"],
  ["oldTag"=>"black greek life","newTag"=>"Black greek life","action"=>"REPLACE"],
  ["oldTag"=>"black land ownership","newTag"=>"Black land ownership","action"=>"REPLACE"],
  ["oldTag"=>"Chapel Hill Freedom Movement","newTag"=>"Freedom Movement","action"=>"REPLACE"],
  ["oldTag"=>"Coach [R.O.] Kornegay","newTag"=>"Coach Kornegay","action"=>"REPLACE"],
  ["oldTag"=>"Coach [Will] Bradshaw","newTag"=>"Coach Bradshaw","action"=>"REPLACE"],
  ["oldTag"=>"community organizing","newTag"=>"organizing","action"=>"REPLACE"],
  ["oldTag"=>"construction work","newTag"=>"construction","action"=>"REPLACE"],
  ["oldTag"=>"MacDougal Elementary School","newTag"=>"McDougle Elementary School","action"=>"REPLACE"],
  ["oldTag"=>"MacDougal Middle School","newTag"=>"McDougle Middle School","action"=>"REPLACE"],
  ["oldTag"=>"Miss Frances Hargraves","newTag"=>"Frances Hargraves","action"=>"REPLACE"],
  ["oldTag"=>"Mr. Bynum Weaver","newTag"=>"Bynum Weaver","action"=>"REPLACE"],
  ["oldTag"=>"Mr. Clark Edgerton","newTag"=>"Clark Egerton","action"=>"REPLACE"],
  ["oldTag"=>"Mr. Clark Egarton","newTag"=>"Clark Egerton","action"=>"REPLACE"],
  ["oldTag"=>"Mr. James Peace","newTag"=>"James Peace","action"=>"REPLACE"],
  ["oldTag"=>"Mr. Macdougal","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Mr. McDougle","newTag"=>"Charles McDougle","action"=>"REPLACE"],
  ["oldTag"=>"Mr. Peace","newTag"=>"James Peace","action"=>"REPLACE"],
  ["oldTag"=>"Mr. Peerman","newTag"=>"Coach Peerman","action"=>"REPLACE"],
  ["oldTag"=>"Mr. R. D. Smith","newTag"=>"R.D. Smith","action"=>"REPLACE"],
  ["oldTag"=>"Mr. R.D. Smith","newTag"=>"R.D. Smith","action"=>"REPLACE"],
  ["oldTag"=>"Mrs. Euzell Smith","newTag"=>"Euzelle Smith","action"=>"REPLACE"],
  ["oldTag"=>"Mrs. R.D. Smith","newTag"=>"Euzelle Smith","action"=>"REPLACE"],
  ["oldTag"=>"Mrs. Zora Rashkiss","newTag"=>"Zora Rashkiss","action"=>"REPLACE"],
  ["oldTag"=>"Ms. Euzelle Smith","newTag"=>"Euzelle Smith","action"=>"REPLACE"],
  ["oldTag"=>"Ms. Hargrave","newTag"=>"Frances Hargraves","action"=>"REPLACE"],
  ["oldTag"=>"Ms. Hargraves","newTag"=>"Frances Hargraves","action"=>"REPLACE"],
  ["oldTag"=>"Ms. Suzie Weaver","newTag"=>"Suzie Weaver","action"=>"REPLACE"],
  ["oldTag"=>"Northside School","newTag"=>"Northside Elementary School","action"=>"REPLACE"],
  ["oldTag"=>"Reverend Manley","newTag"=>"J.R. Manly","action"=>"REPLACE"],
  ["oldTag"=>"Ross Norwood's service station","newTag"=>"Norwood's service station","action"=>"REPLACE"],
  ["oldTag"=>"University of North Carolina","newTag"=>"UNC","action"=>"REPLACE"],
  ["oldTag"=>"University of North Carolina at Chapel Hill","newTag"=>"UNC","action"=>"REPLACE"],
  ["oldTag"=>"Watt's Hotel discrimination","newTag"=>"Watt's Hotel","action"=>"REPLACE"],
  ["oldTag"=>"[low] wages","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"[Ross] Norwood's service station","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"1940s","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"1950s","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"1960s","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"1970s","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"academic achievement","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Achievement gaps","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"African American actresses","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"African American and Diaspora Studies","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"agricultural education","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Airport Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Al McSurely","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"ambulance services","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"American Tobacco","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Armor of God","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Arthur Caldwell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Asheboro school","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Atwater family","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Atwater gym","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Bank of America","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"banks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Battle Lane","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"beauty standards","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Belks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"bellhop","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Bennett and Blocks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Bessy Edwards","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Betty King","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Beverly Mara","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Big John's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Bill Stricklund","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Birmingham AL church bombing","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"black community","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Black owned businesses","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"black traditions","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"blacksmith shop","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Blackwood Family","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Blue Cross Blue Shield","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Bob Gilgor","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"boycotts","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Bradshaw","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"breast cancer","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Brewer Lane","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"brickmason","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Broad Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Brooks Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"bullying","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Business School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Bynum Funeral Home","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"C.W. Stanford Middle School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cadossa McCullen","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Caldwell family","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Caldwell Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Caldwell Street extension","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cameron Avenue","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Campus Health","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carolyn Farrington","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carolyn Home","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"carpentry work","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carr Court","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carr Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro Early School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro Park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Carrboro schools","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Central Carolina Bank of Durham","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Certified Nursing Assistant","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill building codes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill Church of God","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill Country Club","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill daycare","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill Tire Company","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel Hill Town Council","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chapel HIll-Carrboro City School District","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Charlie Foushee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Charlotte","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chase Cafeteria","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chatham County","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Chi Psi","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"childhood educator","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"childhood home","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"children","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Christie Britton","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Church Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Clark Egerton","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"class president","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Clementine Self","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Club Boulevard","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Clyde Durham","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Coach Calter","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Coach Will Bradshaw","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"coal","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"color barriers","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Columbia Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Comic Book Exchange","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"community","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Community Center","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Community Church of Chapel Hill","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Connie Cloak","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cotton Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Country Club Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Craig Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Crest Drive","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Crooks Corner murder","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Current political climate","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Cynthia Hines","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Damascus Church Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"David Caldwell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"David Caldwell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dean Smith","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Deloris Bynum","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Delta Kappa Epsilon","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"democratic party","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"dining hall","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dip Council","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Doretha Purefoy","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dr. Benjamin Mays","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dr. Patterson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Dr. Wayne Sweers","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Draft","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Duke University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Durham Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"E.A. Brown","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Earl Bynum","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"East Chapel Hill High School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"East Franklin Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ed Caldwell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Edwin Caldwell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Elementary school teacher","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Elizabeth Cotten","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Elmer Pendergraft","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Emerson Field","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"eminent domain","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"entrepreneurship","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ephesus Elementary School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Estes Hill Elementary","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Estes Hills","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Estes Hills Elementary","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Eugene Hines","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Eugene Riggsbee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Eugene Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"family finances","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"family history","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fayetteville Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fayetteville State University","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fidelity Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Film","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"financial aid","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"firehoses","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"fish","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fitch Lumber Company","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"following dreams","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fowler Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Franklin County","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Franklin Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"frat court","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"fraternities","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"fraternity house","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Fred Battle","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"future of Northside","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"George Tate","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"George Washington Carver","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Germany","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Gloria Regester Jeter","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Gomains Avenue","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Graham dorm","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Graham street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"grandparents","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Granny Flacks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Granville County","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Gravley Sanatorium","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Greensboro Massacre","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Greensboro Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Griffin Funeral Home","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Grill","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hargraves family","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hargraves Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Harriston Grove School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hattie Mae Foster","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Haw River Baptist [Church]","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hayden Bennie Renwick","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Headstart","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"health care","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hells Angels","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Highway 54 West","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hilliard Caldwell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hillsborough Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Hillside High School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"home","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"homemaker","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Homestead Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Horton High School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"house demolished","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"ice cream parlor","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ike and Tina Turner","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Isaiah Foushee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jackson Scholar","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"James Peace","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"James Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jesse Chavis","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Joe Clark","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Johnnie Perry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Johnny Robinson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Johnson Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Jones Ferry Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Kappa Alpha","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Kappa Sigma","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Karen Parker","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Katherine Council","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Keith Edwards","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Kelly's","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Kennon Cheek","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Kenny Farrington","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Larry Grimm","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Latino","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"leadership","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Lillian Battle","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Lillian Cannon","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Lillian Robinson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Lincoln Lane","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Lindsay Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"low wages","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"low-income students","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Lyon Park","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mahatma Gandhi","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Main Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mallette Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mama Dip","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Marian Cheek Jackson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"marriage","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Martin Luther King assassination","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mary Potter Academy","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mary Scroggs School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"May Marshbanks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"McCauley Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"McDade Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"McMasters Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"medical transportation","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Melinda Lawrence","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Merritt Mill Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Michael Henry Baldwin","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Michael Johnson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Belcher","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Bell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Butler","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Caroline","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Carrie's school","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Clayton","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Clemens","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Davis","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Edwards","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Ester Atwater","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Gerald","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Joyner","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Lee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Lucille Caldwell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Mamie Baldwin","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Marshbanks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Mary Lassiter","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss McMillan","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Minnie D. Turner","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Monroe","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Peace","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Peacock","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Pope","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Robinson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Rogers","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Rosa Holloway","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Smith","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Stanford","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Susie","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Suzy Weaver","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Turner","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Miss Vivian Ingrams","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mitchell Lane","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Morehead Planetarium","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Baldwin","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Bell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Ben Baldwin","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Carson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Christmas","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Cooper","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Echon","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Edmund","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Edmunds","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Edwards","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Egarton","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Egerton","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Farrington","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Fryer","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Goldston","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Holmes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Hubert Robinson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Judas Scales","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Kenny Jones","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Kornegay","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Pickard","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Pickett","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Renwick","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Samuel","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Scales","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Smith","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Stroud","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Tank Connor","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Thrasher","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Todd","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Turner","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Vaughn","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. Weaver","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mr. William","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Barnes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Battle","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Bell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Boyd","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Cecilia Bams","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Clayton","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Clemens","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Clifford","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Edmunds","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Gigi Clemmons","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Gordon","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Hargraves","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Harry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Hogan","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. King","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Lampley","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Lewis","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Manley","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. May Marsh Banks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. McAllister","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Mcdougal","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Milton D. Forfoot","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Peace","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Peerman","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Polk","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Roberson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Robinson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Scales","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Smith","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Smithwick","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Thomasine Kirkland Burthey","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Turner","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Mrs. Vivian Evans [Edmonds]","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. [Charlene M.] Smith","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Barnes","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Basnight","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Clemens","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Clemmons","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Davis","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. French","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Hatchett","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Lillian Robinson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Lucile McDougle","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Lucille Caldwell","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Madge Harry","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Maggie Morphis","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Marsh Banks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Monroe","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Pope","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Post","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ms. Turner","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Myrtle Riggsbee","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"NC Hwy 54","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"neighbors","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"New Jersey","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"New York","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"North Brothers","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"North Carolina Coaches Association","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Northside","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Northside neighborhood","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ophelia Johnson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Orange County","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Otto White","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Padgett's Lane","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"parades","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"parties","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Pearson Elementary School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Peter Leak","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Pittsboro","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"politics","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"President Obama","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Prince Taylor","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Professors","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"PTA","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Purefoy Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"railroad tracks","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"relationships","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"resistance","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"restaurant","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Reverend Jones","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Riley Wilson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Riverside High School","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Robeson County","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rosa Prelout","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Rosemary Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ross Farrington","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"ROTC","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Roy Atwater","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"rural","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Russell Garrett","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Ruth Hope","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"safe places","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"safe-space","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"safety","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"safety patrol","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Sarah Edwards","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"saving money","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"School Lane","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"school news paper","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Scotland County","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Self-Help Credit Union","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Sharmine Baldwin","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"siblings","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Sigma Chi Sorority","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Sigma Ki Fraternity","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Sigma Nu Fraternity","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"singer","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Smith Level Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"South Carolina","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"South Graham Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"sports","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"St. Joseph CME Church","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"St. Joseph’s CME","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Student Union","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Sunset Drive","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Susie Weaver's Gospel Singers","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Sykes Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Terry Carver","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"TESA","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Thanksgiving","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Thomas Hammond","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Thurman Couch","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Tim Tyson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Tom Purefoy","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Trayvon Martin murder","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"truth","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"tutoring","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Umstead Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University Cleaners","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University Lake","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"University Lake Road","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Vance County","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Virginia Carson","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Wade de Graffenreidt","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"waiter","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Wake County","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Warrenton","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"West Franklin Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"West Main Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Whitaker Street","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"white greek life","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"white residents","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Whitehead Circle","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Whitted Junior High","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"William Carter","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"YMCA","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"youth","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"Yvonne Cotton","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"zoning","newTag"=>"","action"=>"REMOVE"],
  ["oldTag"=>"-","newTag"=>"","action"=>"REMOVE"],
];
