version: 2.1
jobs:
  build: # Build CSS files only
    docker:
      - image: circleci/ruby:2.4.2
    working_directory: ~/repo
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "~/repo/htdocs/themes/berlin_mcjc/Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment
          working_directory: ~/repo/htdocs/themes/berlin_mcjc

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "~/repo/htdocs/themes/berlin_mcjc/Gemfile.lock" }}
          paths:
            - ~/repo/htdocs/themes/berlin_mcjc/vendor/bundle

      - run:
          name: Compile SASS
          command: bundle exec compass compile
          working_directory: ~/repo/htdocs/themes/berlin_mcjc

      - persist_to_workspace:
          root: ~/repo
          paths:
            - htdocs/*

  deploy_dev:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

  deploy_prod:
    docker:
      - image: alpine:3.7
      steps:
        - run:
            name: The First Step
            command: |
              echo 'Hello World!'
              echo 'This is the delivery pipeline'

# TODO: Add test steps

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only:
                develop
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only:
                master
