version: 2.1
jobs:
  build: # Build CSS files only
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Install yarn and run prettier
      - restore_cache:
          keys:
            - ndc-yarn-{{ checksum "~/repo/yarn.lock" }}
            - ndc-yarn-

      - run: # Install yarn dependencies
          name: Yarn install
          command: yarn install --production=false

      - save_cache:
          key: ndc-yarn-{{ checksum "~/repo/yarn.lock" }}
          paths:
            - ~/repo/node_modules

      - run:
          name: Prettier
          command: yarn run prettier:check-ci

      - run:
          name: Compile SASS
          command: yarn run build

      - run:
          name: Purge SASS
          command: yarn run purgecss -c purgecss.config.js
          working_directory: ~/repo/

      - persist_to_workspace:
          root: ~/repo
          paths:
            - htdocs/*

  deploy_dev:
    environment:
      - LC_ALL: C
    docker:
      - image: cimg/base:2020.01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "82:83:1b:d5:19:00:e3:7c:58:c6:6f:0c:31:86:e4:4f"
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Enable SSH authentication for remote server
          command: |
            mkdir -p ~/.ssh
            echo "$FROMTHEROCKWALL_IP_ADDRESS ecdsa-sha2-nistp256 $FROMTHEROCKWALL_SSH_RSA_KEY" \>> ~/.ssh/known_hosts
      - run:
          name: Checkout code on dev server
          command: ssh -A $FROMTHEROCKWALL_USER@$FROMTHEROCKWALL_IP_ADDRESS 'cd ~/staging.fromtherockwall.org && git pull origin develop'

      - run:
          name: Copy over compiled css files to dev server
          command: scp -rC *.css $FROMTHEROCKWALL_USER@$FROMTHEROCKWALL_IP_ADDRESS:~/staging.fromtherockwall.org/htdocs/themes/berlin_mcjc/css
          working_directory: /tmp/workspace/htdocs/themes/berlin_mcjc/css

      - run:
          name: Add cache-busting
          command: |
            sed s/COMMIT_HASH/$CIRCLE_SHA1/ commit-hash.base.php > commit-hash.php
            scp -C commit-hash.php $FROMTHEROCKWALL_USER@$FROMTHEROCKWALL_IP_ADDRESS:~/staging.fromtherockwall.org/htdocs/themes/berlin_mcjc/common
          working_directory: /tmp/workspace/htdocs/themes/berlin_mcjc/common

  deploy_prod:
    environment:
      - LC_ALL: C
    docker:
      - image: cimg/base:2020.01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "82:83:1b:d5:19:00:e3:7c:58:c6:6f:0c:31:86:e4:4f"
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Enable SSH authentication for remote server
          command: |
            mkdir -p ~/.ssh
            echo "$FROMTHEROCKWALL_IP_ADDRESS ecdsa-sha2-nistp256 $FROMTHEROCKWALL_SSH_RSA_KEY" \>> ~/.ssh/known_hosts
      - run:
          name: Checkout code on dev server
          command: ssh -A $FROMTHEROCKWALL_USER@$FROMTHEROCKWALL_IP_ADDRESS 'cd ~/fromtherockwall.org && git pull origin master'

      - run:
          name: Copy over compiled css files to dev server
          command: scp -rC *.css $FROMTHEROCKWALL_USER@$FROMTHEROCKWALL_IP_ADDRESS:~/fromtherockwall.org/htdocs/themes/berlin_mcjc/css
          working_directory: /tmp/workspace/htdocs/themes/berlin_mcjc/css

      - run:
          name: Add cache-busting
          command: |
            sed s/COMMIT_HASH/$CIRCLE_SHA1/ commit-hash.base.php > commit-hash.php
            scp -C commit-hash.php $FROMTHEROCKWALL_USER@$FROMTHEROCKWALL_IP_ADDRESS:~/fromtherockwall.org/htdocs/themes/berlin_mcjc/common
          working_directory: /tmp/workspace/htdocs/themes/berlin_mcjc/common

# TODO: Add test steps

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only: master
